# Generated by Django 3.2.9 on 2022-04-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_original', models.CharField(max_length=100, unique=True, verbose_name='Título Original')),
                ('titulo_ingles', models.CharField(max_length=100, unique=True, verbose_name='Título em inglês')),
                ('duracao_do_episodio', models.CharField(max_length=100, verbose_name='Duração do episódio')),
                ('inicio', models.CharField(max_length=100, verbose_name='Data de início')),
                ('status_obra', models.CharField(max_length=100, verbose_name='Status')),
                ('temporada', models.CharField(max_length=100, verbose_name='Temporada de lançamento')),
                ('estudio', models.CharField(max_length=100, verbose_name='Estudio')),
                ('origem', models.CharField(max_length=100, verbose_name='Pais de origem')),
                ('generos', models.CharField(max_length=100, verbose_name='Gêneros')),
                ('imagens', models.ImageField(upload_to='media')),
                ('banner', models.ImageField(upload_to='media')),
                ('descricao', models.CharField(max_length=1000, verbose_name='Descrição')),
            ],
        ),
    ]
